### PR TITLE
Updating NEMS to use bulk formula for purely water points for DATM

### PR DESCRIPTION
**Pull request by junwang-noaa**
Related PRs:

[NEMS #69](https://github.com/NOAA-EMC/NEMS/pull/69)

### CODE REVIEW

**Review by binli2337 — APPROVED** [review]
Looks good.

**Comment by DeniseWorthen** [comment]
I'm confused---don't we normally update the component to the develop branch and then update the app?

**Comment by junwang-noaa** [comment]
Yes, We do. NEMS will be merged soon, this is for code review.

**Review by DeniseWorthen — APPROVED** [review]
approve

**Pull request merged**
